### ISSUE TITLE
Layout in example app

### ISSUE THREAD

**Issue by dnlkoch** [terrestris/react-geo-ws#13]
The layout of the current example app is somehow broken:
  * A scrollbar is visible beneath the toolbar after using the search combo.
  * The map isn't rendered correctly on init, maybe a call to `map.updateSize()` is missing.

![app-layout-issues](https://user-images.githubusercontent.com/1137620/52707651-71a1d600-2f88-11e9-8922-830a86581113.png)

**Comment by jansule** [comment]
@dnlkoch could not reproduce bug.
No scrollbar visible.

Tested on: 
OSGeo Live 12.0
firefox 61.01
resolutions: (1024x768) & (1920x980)
